### ISSUE TITLE
[Issue] Can't donate with PayPal

### ISSUE THREAD

**Issue by ploedman** [death-claw/vripper-project#10]
Just wanted to say thanks, with a small donation.
But, after confirming the amount of money, I get an error, that donation are only accepted over your Website.

![Screenshot_2020-06-26 Donate](https://user-images.githubusercontent.com/345180/85823907-ce1d2400-b77e-11ea-826a-517fb5387ad0.png)

Sorry for the German text in the screenshot, but it was not possible for me to change the language to English.

**Comment by death-claw** [comment]
Am having trouble setting this up, I will look for an alternative solution
