### ISSUE TITLE
"Error creating bean with name 'clipboardService' defined in URL" upon opening

### ISSUE THREAD

**Issue by Gerbzzz** [death-claw/vripper-project#103]
VRipper 4.2.0, even after reinstall, upon opening immediately crashes and spits out the following error.
[VRipperError.txt](https://github.com/death-claw/vripper-project/files/11997132/VRipperError.txt)

**Comment by delta7890** [comment]
Same issue for me as well.

**Comment by death-claw** [comment]
Probably data corruption on vripper folder like @delta7890  mentioned.
