### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by outohi** [death-claw/vripper-project#129]
win11 -how to deal this?
<img width="885" alt="屏幕截图 2023-10-07 220644" src="https://github.com/death-claw/vripper-project/assets/121934256/24bf816a-a538-4fe9-9a53-ac171cf2fef0">

**Comment by outohi** [comment]
in another WIN10PC it works well

**Comment by death-claw** [comment]
This is a connection problem, are you sure you have access to the website

**Comment by outohi** [comment]
> This is a connection problem, are you sure you have access to the website

of course...settings is same to win10 pc .
<img width="886" alt="image" src="https://github.com/death-claw/vripper-project/assets/121934256/68116b77-4a1a-45fb-aff6-1e10a6f4fe40">

**Comment by outohi** [comment]
[vripper.log](https://github.com/death-claw/vripper-project/files/12908428/vripper.log)

**Comment by Rounlet** [comment]
I also have a similar problem.
I usually use the DPI detour program, but this time I turned it off, and this is the result.
Even without the DPI detour, the main site is still well connected,
and I still have the same problem when I try changing to another accessible proxy.
![image](https://github.com/death-claw/vripper-project/assets/47098778/e41aa06f-7026-46bf-87db-524c0c63b3d5)
