### ISSUE TITLE
Git directory error

### ISSUE THREAD

**Issue by BoJockel** [death-claw/vripper-project#15]
I get the following error on building the server version:

[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:3.0.0:revision (default) on project vripper-server: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]

Git is installed and Maven 3.6.3 is been used.

**Comment by life-claw** [comment]
@BoJockel maybe you downloaded the source as a zip file instead of cloning the repository with Git?

**Comment by BoJockel** [comment]
Ok you got it right! But i don't rly understand where the difference is? Have you a explanation or is it too complicated?
And i found out the ripper just runs with java version 11. Maybe you could update the requirements? Thanks for the help!

**Comment by death-claw** [comment]
Java 11 is a long term support version, it works fine and i don't see why I should upgrade.
Regarding the error you got, the build plugins need to extract some information from the git repo (branch, revision...), but sinc you did not clone the repo, those information are missing and the build plugin failed.

If you intend to build the app, you must clone it first, that will setup a correct local repo
