### ISSUE TITLE
Nothing after installation vripper 5.2.0

### ISSUE THREAD

**Issue by tisme1250** [death-claw/vripper-project#161]
Hello

I've just installed vripper 5.2.0 qur windows 11, but nothing happens when I copy the link from a thread into the little window that appears after clicking on the green cross at the top.

Thanks for help !

**Comment by derickso** [comment]
Same

**Comment by Miustone** [comment]
Same here...

**Comment by death-claw** [comment]
You are being blocked by cloudflare, use the main site instead

**Comment by tisme1250** [comment]
Hello

Thxxx for interest

What do you mean with main site ?

Thxxx
