### ISSUE TITLE
General tab showing a mashup of multiple posts

### ISSUE THREAD

**Issue by twwat** [death-claw/vripper-project#176]
The 'General' tab at the bottom of the screen shows a combination of:

- Currently selected post (_Post Link_, _Posted By_, _Title_, _More titles_, _Hosts_)
- Post with the most recent activity (_Status_, _Path_, _Total_)
- Info that doesn't match any posts (_Added On_ date)

Example screenshot 1:
![image](https://github.com/death-claw/vripper-project/assets/157976730/c173e04f-e109-4b3f-ad0c-20574f645e03)

Example screenshot 2:
![image](https://github.com/death-claw/vripper-project/assets/157976730/181240b2-7951-418a-b039-fc558e0908e1)

The 'Added On' date must be from an earlier/deleted post or something, as it never changes and is 23 minutes prior to the earliest post on the list:
![image](https://github.com/death-claw/vripper-project/assets/157976730/074b8d02-8783-4b65-adf1-df0583cb0fa7)

**Comment by death-claw** [comment]
I couldn't reproduce, but I'll keep this in mind
