### ISSUE TITLE
'npm run dist' failed.

### ISSUE THREAD

**Issue by DJJones66** [death-claw/vripper-project#18]
Full Error:
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:npm (npm run build) on project vripper-electron: Failed to run task: 'npm run dist' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:npm (npm run build) on project vripper-electron: Failed to run task

I am using windows, also do not use these kind of tools since mainly a c# developer.  I did try changing the node and npm versions to match mine based on research but that and nothing else seems to resolve the issue.  

Any help to resolve the issue would be appreciated.

**Comment by DJJones66** [comment]
Any idea how this can be resolved or where should look?

**Comment by death-claw** [comment]
Is there another error message detailing further what went wrong ?
There sould be more information printed on the console

**Comment by DJJones66** [comment]
Adding the log file and some of the console since it gives a little additional info..

[ERROR] 'jlink' is not recognized as an internal or external command,
[ERROR] operable program or batch file.
[ERROR] child_process.js:669
[ERROR]     throw err;
[ERROR]     ^
[ERROR]
[ERROR] Error: Command failed: jlink --no-header-files --no-man-pages --compress=2 --strip-debug --add-modules java.base,java.desktop,java.instrument,java.management,java.naming,java.prefs,java.rmi,java.scripting,java.security.jgss,java.sql,jdk.httpserver,jdk.unsupported,jdk.crypto.ec --output java-runtime
[ERROR] 'jlink' is not recognized as an internal or external command,
[ERROR]
[ERROR] operable program or batch file.
[ERROR]
[ERROR]
[ERROR]     at checkExecSyncError (child_process.js:630:11)
[ERROR]     at execSync (child_process.js:666:15)
[ERROR]     at Object.<anonymous> (C:\Development\VRipper\vripper-v3.0.10\vripper-project\vripper-electron\pre-build.js:21:1)
[ERROR]     at Module._compile (internal/modules/cjs/loader.js:1138:30)
[ERROR]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
[ERROR]     at Module.load (internal/modules/cjs/loader.js:986:32)
[ERROR]     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
[ERROR]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
[ERROR]     at internal/main/run_main_module.js:17:47 {
[ERROR]   status: 1,
[ERROR]   signal: null,
[ERROR]   output: [
[ERROR]     null,
[ERROR]     <Buffer >,
[ERROR]     <Buffer 27 6a 6c 69 6e 6b 27 20 69 73 20 6e 6f 74 20 72 65 63 6f 67 6e 69 7a 65 64 20 61 73 20 61 6e 20 69 6e 74 65 72 6e 61 6c 20 6f 72 20 65 78 74 65 72 6e ... 46 more bytes>
[ERROR]   ],
[ERROR]   pid: 95644,
[ERROR]   stdout: <Buffer >,
[ERROR]   stderr: <Buffer 27 6a 6c 69 6e 6b 27 20 69 73 20 6e 6f 74 20 72 65 63 6f 67 6e 69 7a 65 64 20 61 73 20 61 6e 20 69 6e 74 65 72 6e 61 6c 20 6f 72 20 65 78 74 65 72 6e ... 46 more bytes>
[ERROR] }
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! vripper-electron@3.0.10 dist: `node pre-build.js && electron-builder`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the vripper-electron@3.0.10 dist script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR]



[2021-01-13T13_18_24_511Z-debug.log](https://github.com/death-claw/vripper-project/files/5808817/2021-01-13T13_18_24_511Z-debug.log)

**Comment by DJJones66** [comment]
I did wonder if perhaps the issue was the fact I downloaded the code vs cloned it.  It did solve one issue due to the server not having a .git file however the main issue at the end is still there..  I also created a dump of the console just in case it helps.  I know when I am coding, more info the better.
[console.log](https://github.com/death-claw/vripper-project/files/5809110/console.log)

**Comment by death-claw** [comment]
@DJJones66 
On which OS are you running the build command ?
From the output you posted it seems that you have a command missing (jlink).
Make sure that you have **JDK11** installed on your system, you may be running some older JDK, maybe 8 ?
Also if you are on a linux environment, make sure you have the command **strip** installed, installing it depends on your distro, or you may already have it

**Comment by DJJones66** [comment]
Windows 10 Pro (Updated).  I did wonder if it was a JDK issue based on some googling.  I will update to JDK11 and try again.  Thank you (crosses fingers)

**Comment by DJJones66** [comment]
It did get a little further but basically ended with the same kind of error, I did check for the JDK installed (11.0.10)

I attached the log file.  Thanks you
[Debug.txt](https://github.com/death-claw/vripper-project/files/5896319/Debug.txt)

**Comment by death-claw** [comment]
You have to put the JDK bin folder in the PATH environment variable
