### ISSUE TITLE
5.5.0 Data heavy logging with large numbers of links

### ISSUE THREAD

**Issue by madrooky** [death-claw/vripper-project#180]
When adding a large number of links, like more than 1k, the logging goes absolutely nuts. 

![image](https://github.com/death-claw/vripper-project/assets/131664307/43c1a745-263c-4229-b67c-28af150a5136)

Logs are constantly written and deleted and the list seen above is in constant movement. My small 500GB SSD with roughly 80GB free space is partly filled up completely.

![image](https://github.com/death-claw/vripper-project/assets/131664307/1f9743bb-549e-4ee8-93dc-399a2bec182d)

Don't know what the logging actually does and if its necessary.

**Comment by madrooky** [comment]
After a while of never ending logging operations I ended the program and restarted. Some errors came up i clicked away unfortunately. But it seemed to be errors regarding empty threads. The download list is still complete as it was when I quit the app.
But I have to delete about 40GB of log files manually. 

![image](https://github.com/death-claw/vripper-project/assets/131664307/b50d2719-5db3-4d44-bb5d-f950b816f4b7)

Its seems the downloads in the list can be processed normally.
So the excessive logging does not seem to serve any obvious purpose.

**Comment by death-claw** [comment]
I'll check if there's some useless logs and maybe review the archive policy to reduce the size.
The thing here is I suspect that the app is put in heavy load, i think you are loading a long list of posts, most likely the app is crashing and logging a lot of errors, that's probably why the size ballooned quickly. this may be relates to #179

**Comment by madrooky** [comment]
> I'll check if there's some useless logs and maybe review the archive policy to reduce the size. The thing here is I suspect that the app is put in heavy load, i think you are loading a long list of posts, most likely the app is crashing and logging a lot of errors, that's probably why the size ballooned quickly. this may be relates to #179

The one instance with this excessive logging I was quickly adding batches of links until the list was around 1.5k entries. The errors from the other post are unrelated, as they pop up almost every time i add a batch of the typical 25 links from a page.

Since that above happened once I restrain myself a bit with the size of download jobs... :D

Thought about using jdownloader again but I want to leave a like per thread I download^^

One thing I thought could be helpful in general with scraping for bigger data sizes would be to slow the whole process down in a way to prevent the app using too much resources and possibly trigger the hoster to lock the IP temporarily.
A concrete idea would be to set a max number of active threads, and withhold any links exceeding that number in a cache until one of the active threads finishes. But that might require having an option for automatic cleanup for unfinished threads, so the process can run in the background without supervision.
