### ISSUE TITLE
Debian 10, vripper not working via the appimage

### ISSUE THREAD

**Issue by SMooxx** [death-claw/vripper-project#36]
Both AppImage from release page or my own-built one don't work.
When I double click the AppImage file, nothing shows up.

When I try to run it from shell, it has the following error:
`FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_VRippelF2jEt/chrome-sandbox is owned by root and has mode 4755.
`
but at /tmp/.mount_VRippelF2jEt/, there is no chrome-sandbox file or folder at all.

**Comment by SMooxx** [comment]
on debian 10. can't install he latest .deb file. 

shell says:
``dpkg-deb: error: archive vripper-linux-4.3.0_amd64.deb  to control.tar.zst used unkown compress method, aborted
dpkg: processing vripper-linux-4.3.0_amd64.deb (--install) error：
 dpkg-deb --control error status 2
 ``

**Comment by slrslr** [comment]
> control.tar.zst used unkown compress method

I [red](https://unix.stackexchange.com/a/669008) that this error which is produced by "sudo dpkg -i file.deb" is caused by older dpkg not supporting zst compression used by the .deb file. Here is a 3 commands workaround to repack it and install:

> cd /path/to/downloaded/vriperdebfile/
> ar x vripper*.deb;zstd -d < control.tar.zst | xz > control.tar.xz;zstd -d < data.tar.zst | xz > data.tar.xz;ar -m -c -a sdsd /tmp/some-package.deb debian-binary control.tar.xz data.tar.xz;rm debian-binary control.tar.xz data.tar.xz control.tar.zst data.tar.zst;
> sudo dpkg -i /tmp/some-package.deb
