### ISSUE TITLE
[suggestion] alternative title toggle

### ISSUE THREAD

**Issue by CaptnSeraph** [death-claw/vripper-project#48]
Some longer threads have better alternative titles for tagging purposes, rather than having to set this individually, a toggle to prefer this alternative title would be useful

**Comment by elvisef** [comment]
Correct. I don't know what is the column for alternative title for, if I cannot change this for auto-naming folders.
How to change to alternative titles naming ?
If the alternative title is "none" (not available) it would give a basic title of course.

**Comment by protogen** [comment]
I would like to add my support for this feature request.  :-)

As explained in my [VG post](https://vipergirls.to/threads/4660537-VRipper-(Cross-platform-Gallery-Ripper)?p=154920023&viewfull=1#post154920023), I feel the **Rename** and **Use alternative title** functions are essential.  As @CaptnSeraph mentioned, when downloading multiple sets from long threads (like [this one](https://vipergirls.to/threads/3746955-ClubSeventeen-Models-(Complete-Model-Sets-for-each-Model-HC-SC-GG))) a rename function is an absolute necessity.

The way this worked in v3.5.4  was excellent (toolbar button and context menu).  Screenshot below.

![001](https://github.com/death-claw/vripper-project/assets/3028907/4897a9e5-dfe3-464e-8bee-47d71e730b75)
