### ISSUE TITLE
Unable to download from imagebam.com

### ISSUE THREAD

**Issue by GiHa** [death-claw/vripper-project#65]
Like title says, its unable to download from imagebam.com 

Example: https://www.imagebam.com/image/54ae07319618490
From: https://vipergirls.to/threads/600140-Artistic-gt-gt-Tasteful-gt-gt-Nude-gt-gt-Erotic-gt-gt-Full-Sets-gt-gt-gt-(Collection)?p=3903483&viewfull=1#post3903483

Log:
Message
Failed to download http://www.imagebam.com/image/54ae07319618490
 tn.mnlr.vripper.exception.DownloadException: tn.mnlr.vripper.exception.HostException: Xpath '//img[contains(@class,'main-image')]' cannot be found in 'http://www.imagebam.com/image/54ae07319618490'
	at tn.mnlr.vripper.download.DownloadJob.download(DownloadJob.java:172)
	at tn.mnlr.vripper.download.DownloadJob.run(DownloadJob.java:253)
	at net.jodah.failsafe.Functions.lambda$supplierOf$12(Functions.java:296)
	at net.jodah.failsafe.Functions.lambda$resultSupplierOf$11(Functions.java:283)
	at net.jodah.failsafe.internal.executor.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:67)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:117)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:319)
	at net.jodah.failsafe.FailsafeExecutor.run(FailsafeExecutor.java:219)
	at tn.mnlr.vripper.download.DownloadJobWrapper.run(DownloadJobWrapper.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: tn.mnlr.vripper.exception.HostException: Xpath '//img[contains(@class,'main-image')]' cannot be found in 'http://www.imagebam.com/image/54ae07319618490'
	at tn.mnlr.vripper.host.ImageBamHost.getNameAndUrl(ImageBamHost.java:71)
	at tn.mnlr.vripper.download.DownloadJob.download(DownloadJob.java:101)
	... 11 more

**Comment by NeevorPL** [comment]
+1

**Comment by BootrosBootros** [comment]
Logic has changed on imagebam.  

ImageBamHost.java:
```
try {
      log.debug(String.format("Looking for xpath expression %s in %s", CONTINUE_XPATH, url));
      if (xpathService.getAsNode(doc, CONTINUE_XPATH) != null) {
        // Button detected. No need to actually click it, just make the call again.
        response = hostService.getResponse(url, context);
        doc = response.getDocument();
      }
```
assumes that a reload clears the ad.  It doesn't anymore, reload keeps the "Continue to your image" link that needs to be clicked.

ImageVenueHost.java and AcidimgHost.java both have code sections that seem to get past these blockers.  Maybe that code can be leveraged?

**Comment by RsX88** [comment]
Here is the code that works for me
it goes in vripper-project-master\vripper-server\src\main\java\tn\mnlr\vripper\host\ImageBamHost.java

`package tn.mnlr.vripper.host;

import lombok.extern.slf4j.Slf4j;
import org.apache.http.client.protocol.HttpClientContext;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import tn.mnlr.vripper.exception.HostException;
import tn.mnlr.vripper.exception.XpathException;
import tn.mnlr.vripper.services.HostService;
import tn.mnlr.vripper.services.XpathService;

import java.time.Instant;

import org.apache.http.NameValuePair;
import org.apache.http.client.HttpClient;
import org.apache.http.client.entity.UrlEncodedFormEntity;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.util.EntityUtils;
import tn.mnlr.vripper.services.ConnectionService;
import tn.mnlr.vripper.services.HtmlProcessorService;


import java.util.Optional;
import java.util.UUID;

import java.io.*;

import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.DefaultHttpClient;

@Service
@Slf4j
public class ImageBamHost extends Host {

  private static final String host = "imagebam.com";
  private static final String IMG_XPATH = "//img[contains(@class,'main-image')]";
  private static final String CONTINUE_XPATH = "//*[contains(text(), 'Continue')]";
  
  private final ConnectionService cm;
  private final HostService hostService;
  private final XpathService xpathService;
  private final HtmlProcessorService htmlProcessorService;

  @Autowired
  public ImageBamHost(
      ConnectionService cm,
      HostService hostService,
      XpathService xpathService,
      HtmlProcessorService htmlProcessorService) {
    this.cm = cm;
    this.hostService = hostService;
    this.xpathService = xpathService;
    this.htmlProcessorService = htmlProcessorService;
  }

  @Override
  public String getHost() {
    return host;
  }

  @Override
  public String getLookup() {
    return host;
  }

  @Override
  public HostService.NameUrl getNameAndUrl(final String url, final HttpClientContext context)
      throws HostException {

    Document doc = hostService.getResponse(url, context).getDocument();

	  
	HttpClient client = cm.getClient().build();
	HttpGet httpGet = new HttpGet(url);
	httpGet.addHeader("Referer", url);
	long expireTime=Instant.now().getEpochSecond();
	expireTime+=6*60*60*1000;
	httpGet.addHeader("Cookie", "nsfw_inter=1" + expireTime + "; path=/");//--header="Cookie: nsfw_inter=11681491300; path=/"
	HttpResponse httpResponse;
	
	try {
		httpResponse = client.execute(httpGet);
	} catch (Exception e) {
		throw new HostException(e);
	}
	  
	try {
		doc = htmlProcessorService.clean(EntityUtils.toString(httpResponse.getEntity()));
	} catch (Exception e) {
		throw new HostException(e);
	}

    Node imgNode;
    try {
      log.debug(String.format("Looking for xpath expression %s in %s", IMG_XPATH, url));
      imgNode = xpathService.getAsNode(doc, IMG_XPATH);
    } catch (XpathException e) {
      throw new HostException(e);
    }

    if (imgNode == null) {
      throw new HostException(String.format("Xpath '%s' cannot be found in '%s'", IMG_XPATH, url));
    }

    try {
      log.debug(String.format("Resolving name and image url for %s", url));
      String imgTitle =
          Optional.ofNullable(imgNode.getAttributes().getNamedItem("alt"))
              .map(e -> e.getTextContent().trim())
              .orElse("");
      String imgUrl =
          Optional.ofNullable(imgNode.getAttributes().getNamedItem("src"))
              .map(e -> e.getTextContent().trim())
              .orElse("");
      String defaultName = UUID.randomUUID().toString();

      int index = imgUrl.lastIndexOf('/');
      if (index != -1 && index < imgUrl.length()) {
        defaultName = imgUrl.substring(imgUrl.lastIndexOf('/') + 1);
      }

      return new HostService.NameUrl(imgTitle.isEmpty() ? defaultName : imgTitle, imgUrl);
    } catch (Exception e) {
      throw new HostException("Unexpected error occurred", e);
    }
  }
}`

**Comment by GiHa** [comment]
> Here is the code that works for me it goes in vripper-project-master\vripper-server\src\main\java\tn\mnlr\vripper\host\ImageBamHost.java
> 
> [ImageBam_Host.zip](https://github.com/death-claw/vripper-project/files/9284264/ImageBam_Host.zip)

Confirmed

**Comment by stoutsock** [comment]
I've reviewed this today as I'm still having the issue. I'm finding that this is now not working - I've found that line 83 which reads in the fix:

`httpGet.addHeader("Cookie", "nsfw_inter=1" + expireTime + "; path=/");//--header="Cookie: nsfw_inter=11681491300; path=/"`

should now read:

`httpGet.addHeader("Cookie", "nsfw_inter=1");`

It looks as though the intermediate stage is looking for the nsfw_inter=1 cookie which then bypasses the intermediate page.
