### ISSUE TITLE
Question: How do I run the program after compile

### ISSUE THREAD

**Issue by poundonu** [death-claw/vripper-project#77]
Hello, great product. I have finally built all the components after quite a bit of troubleshooting, but now I can't figure out how to run the program like I did with the older VRipper.exe. The compiling with mvn doesn't seem to have created an exe file. Sorry if I've posted this in the wrong place, but I can't go any further it looks like. Thanks in advance.

**Comment by death-claw** [comment]
@poundonu please use v4.x, I won't work on v3.x no more
