### ISSUE TITLE
Desktop Integration in v4.x

### ISSUE THREAD

**Issue by PsychoSid** [death-claw/vripper-project#87]
Thanks for the continued work.

v3.x had desktop integration and would listen for URL's on the clipboard this option appears missing from v4.x is it possible to add ?

Also I have "Clear Finished" setting enabled which doesn't clear finished downloads in the UI and then attempting to remove manually throws an exception in 

```
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
```

**Comment by death-claw** [comment]
desktop integration will come later.

"Clear Finished" is a ui bug, it will be fixed later

**Comment by death-claw** [comment]
Will open seperate issues for above
